// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeBuilding.proto

package protofiles;

public final class EmployeeBuilding {
  private EmployeeBuilding() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protofiles.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 Employee_ID = 1;</code>
     * @return The employeeID.
     */
    int getEmployeeID();

    /**
     * <code>string First_Name = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string First_Name = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string Last_Name = 3;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string Last_Name = 3;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string Email = 4;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string Email = 4;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string Department = 5;</code>
     * @return The department.
     */
    java.lang.String getDepartment();
    /**
     * <code>string Department = 5;</code>
     * @return The bytes for department.
     */
    com.google.protobuf.ByteString
        getDepartmentBytes();

    /**
     * <code>string Building_Code = 6;</code>
     * @return The buildingCode.
     */
    java.lang.String getBuildingCode();
    /**
     * <code>string Building_Code = 6;</code>
     * @return The bytes for buildingCode.
     */
    com.google.protobuf.ByteString
        getBuildingCodeBytes();

    /**
     * <code>.protofiles.Person.Floor Floor_Number = 7;</code>
     * @return The enum numeric value on the wire for floorNumber.
     */
    int getFloorNumberValue();
    /**
     * <code>.protofiles.Person.Floor Floor_Number = 7;</code>
     * @return The floorNumber.
     */
    protofiles.EmployeeBuilding.Person.Floor getFloorNumber();
  }
  /**
   * Protobuf type {@code protofiles.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protofiles.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      firstName_ = "";
      lastName_ = "";
      email_ = "";
      department_ = "";
      buildingCode_ = "";
      floorNumber_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              employeeID_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              department_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              buildingCode_ = s;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              floorNumber_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protofiles.EmployeeBuilding.internal_static_protofiles_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protofiles.EmployeeBuilding.internal_static_protofiles_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protofiles.EmployeeBuilding.Person.class, protofiles.EmployeeBuilding.Person.Builder.class);
    }

    /**
     * Protobuf enum {@code protofiles.Person.Floor}
     */
    public enum Floor
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>ONE = 1;</code>
       */
      ONE(1),
      /**
       * <code>TWO = 2;</code>
       */
      TWO(2),
      /**
       * <code>THREE = 3;</code>
       */
      THREE(3),
      /**
       * <code>FOUR = 4;</code>
       */
      FOUR(4),
      /**
       * <code>FIVE = 5;</code>
       */
      FIVE(5),
      /**
       * <code>SIX = 6;</code>
       */
      SIX(6),
      /**
       * <code>SEVEN = 7;</code>
       */
      SEVEN(7),
      /**
       * <code>EIGHT = 8;</code>
       */
      EIGHT(8),
      /**
       * <code>NINE = 9;</code>
       */
      NINE(9),
      /**
       * <code>TEN = 10;</code>
       */
      TEN(10),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>ONE = 1;</code>
       */
      public static final int ONE_VALUE = 1;
      /**
       * <code>TWO = 2;</code>
       */
      public static final int TWO_VALUE = 2;
      /**
       * <code>THREE = 3;</code>
       */
      public static final int THREE_VALUE = 3;
      /**
       * <code>FOUR = 4;</code>
       */
      public static final int FOUR_VALUE = 4;
      /**
       * <code>FIVE = 5;</code>
       */
      public static final int FIVE_VALUE = 5;
      /**
       * <code>SIX = 6;</code>
       */
      public static final int SIX_VALUE = 6;
      /**
       * <code>SEVEN = 7;</code>
       */
      public static final int SEVEN_VALUE = 7;
      /**
       * <code>EIGHT = 8;</code>
       */
      public static final int EIGHT_VALUE = 8;
      /**
       * <code>NINE = 9;</code>
       */
      public static final int NINE_VALUE = 9;
      /**
       * <code>TEN = 10;</code>
       */
      public static final int TEN_VALUE = 10;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Floor valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Floor forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return ONE;
          case 2: return TWO;
          case 3: return THREE;
          case 4: return FOUR;
          case 5: return FIVE;
          case 6: return SIX;
          case 7: return SEVEN;
          case 8: return EIGHT;
          case 9: return NINE;
          case 10: return TEN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Floor>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Floor> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Floor>() {
              public Floor findValueByNumber(int number) {
                return Floor.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protofiles.EmployeeBuilding.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final Floor[] VALUES = values();

      public static Floor valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Floor(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protofiles.Person.Floor)
    }

    public static final int EMPLOYEE_ID_FIELD_NUMBER = 1;
    private int employeeID_;
    /**
     * <code>int32 Employee_ID = 1;</code>
     * @return The employeeID.
     */
    @java.lang.Override
    public int getEmployeeID() {
      return employeeID_;
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string First_Name = 2;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string First_Name = 2;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string Last_Name = 3;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string Last_Name = 3;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>string Email = 4;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string Email = 4;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPARTMENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object department_;
    /**
     * <code>string Department = 5;</code>
     * @return The department.
     */
    @java.lang.Override
    public java.lang.String getDepartment() {
      java.lang.Object ref = department_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        department_ = s;
        return s;
      }
    }
    /**
     * <code>string Department = 5;</code>
     * @return The bytes for department.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDepartmentBytes() {
      java.lang.Object ref = department_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        department_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUILDING_CODE_FIELD_NUMBER = 6;
    private volatile java.lang.Object buildingCode_;
    /**
     * <code>string Building_Code = 6;</code>
     * @return The buildingCode.
     */
    @java.lang.Override
    public java.lang.String getBuildingCode() {
      java.lang.Object ref = buildingCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildingCode_ = s;
        return s;
      }
    }
    /**
     * <code>string Building_Code = 6;</code>
     * @return The bytes for buildingCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBuildingCodeBytes() {
      java.lang.Object ref = buildingCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildingCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLOOR_NUMBER_FIELD_NUMBER = 7;
    private int floorNumber_;
    /**
     * <code>.protofiles.Person.Floor Floor_Number = 7;</code>
     * @return The enum numeric value on the wire for floorNumber.
     */
    @java.lang.Override public int getFloorNumberValue() {
      return floorNumber_;
    }
    /**
     * <code>.protofiles.Person.Floor Floor_Number = 7;</code>
     * @return The floorNumber.
     */
    @java.lang.Override public protofiles.EmployeeBuilding.Person.Floor getFloorNumber() {
      @SuppressWarnings("deprecation")
      protofiles.EmployeeBuilding.Person.Floor result = protofiles.EmployeeBuilding.Person.Floor.valueOf(floorNumber_);
      return result == null ? protofiles.EmployeeBuilding.Person.Floor.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (employeeID_ != 0) {
        output.writeInt32(1, employeeID_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      if (!getDepartmentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, department_);
      }
      if (!getBuildingCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, buildingCode_);
      }
      if (floorNumber_ != protofiles.EmployeeBuilding.Person.Floor.UNKNOWN.getNumber()) {
        output.writeEnum(7, floorNumber_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (employeeID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, employeeID_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      if (!getDepartmentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, department_);
      }
      if (!getBuildingCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, buildingCode_);
      }
      if (floorNumber_ != protofiles.EmployeeBuilding.Person.Floor.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, floorNumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protofiles.EmployeeBuilding.Person)) {
        return super.equals(obj);
      }
      protofiles.EmployeeBuilding.Person other = (protofiles.EmployeeBuilding.Person) obj;

      if (getEmployeeID()
          != other.getEmployeeID()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getDepartment()
          .equals(other.getDepartment())) return false;
      if (!getBuildingCode()
          .equals(other.getBuildingCode())) return false;
      if (floorNumber_ != other.floorNumber_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EMPLOYEE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEmployeeID();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + DEPARTMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDepartment().hashCode();
      hash = (37 * hash) + BUILDING_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingCode().hashCode();
      hash = (37 * hash) + FLOOR_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + floorNumber_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protofiles.EmployeeBuilding.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protofiles.EmployeeBuilding.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protofiles.EmployeeBuilding.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protofiles.EmployeeBuilding.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protofiles.EmployeeBuilding.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protofiles.EmployeeBuilding.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protofiles.EmployeeBuilding.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protofiles.EmployeeBuilding.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protofiles.EmployeeBuilding.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protofiles.EmployeeBuilding.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protofiles.EmployeeBuilding.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protofiles.EmployeeBuilding.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protofiles.EmployeeBuilding.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protofiles.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protofiles.Person)
        protofiles.EmployeeBuilding.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protofiles.EmployeeBuilding.internal_static_protofiles_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protofiles.EmployeeBuilding.internal_static_protofiles_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protofiles.EmployeeBuilding.Person.class, protofiles.EmployeeBuilding.Person.Builder.class);
      }

      // Construct using protofiles.EmployeeBuilding.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        employeeID_ = 0;

        firstName_ = "";

        lastName_ = "";

        email_ = "";

        department_ = "";

        buildingCode_ = "";

        floorNumber_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protofiles.EmployeeBuilding.internal_static_protofiles_Person_descriptor;
      }

      @java.lang.Override
      public protofiles.EmployeeBuilding.Person getDefaultInstanceForType() {
        return protofiles.EmployeeBuilding.Person.getDefaultInstance();
      }

      @java.lang.Override
      public protofiles.EmployeeBuilding.Person build() {
        protofiles.EmployeeBuilding.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protofiles.EmployeeBuilding.Person buildPartial() {
        protofiles.EmployeeBuilding.Person result = new protofiles.EmployeeBuilding.Person(this);
        result.employeeID_ = employeeID_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.email_ = email_;
        result.department_ = department_;
        result.buildingCode_ = buildingCode_;
        result.floorNumber_ = floorNumber_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protofiles.EmployeeBuilding.Person) {
          return mergeFrom((protofiles.EmployeeBuilding.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protofiles.EmployeeBuilding.Person other) {
        if (other == protofiles.EmployeeBuilding.Person.getDefaultInstance()) return this;
        if (other.getEmployeeID() != 0) {
          setEmployeeID(other.getEmployeeID());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getDepartment().isEmpty()) {
          department_ = other.department_;
          onChanged();
        }
        if (!other.getBuildingCode().isEmpty()) {
          buildingCode_ = other.buildingCode_;
          onChanged();
        }
        if (other.floorNumber_ != 0) {
          setFloorNumberValue(other.getFloorNumberValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protofiles.EmployeeBuilding.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protofiles.EmployeeBuilding.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int employeeID_ ;
      /**
       * <code>int32 Employee_ID = 1;</code>
       * @return The employeeID.
       */
      @java.lang.Override
      public int getEmployeeID() {
        return employeeID_;
      }
      /**
       * <code>int32 Employee_ID = 1;</code>
       * @param value The employeeID to set.
       * @return This builder for chaining.
       */
      public Builder setEmployeeID(int value) {
        
        employeeID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Employee_ID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmployeeID() {
        
        employeeID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string First_Name = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string First_Name = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string First_Name = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string First_Name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string First_Name = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string Last_Name = 3;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Last_Name = 3;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Last_Name = 3;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Last_Name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string Last_Name = 3;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string Email = 4;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Email = 4;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Email = 4;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Email = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string Email = 4;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object department_ = "";
      /**
       * <code>string Department = 5;</code>
       * @return The department.
       */
      public java.lang.String getDepartment() {
        java.lang.Object ref = department_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          department_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Department = 5;</code>
       * @return The bytes for department.
       */
      public com.google.protobuf.ByteString
          getDepartmentBytes() {
        java.lang.Object ref = department_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          department_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Department = 5;</code>
       * @param value The department to set.
       * @return This builder for chaining.
       */
      public Builder setDepartment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        department_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Department = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDepartment() {
        
        department_ = getDefaultInstance().getDepartment();
        onChanged();
        return this;
      }
      /**
       * <code>string Department = 5;</code>
       * @param value The bytes for department to set.
       * @return This builder for chaining.
       */
      public Builder setDepartmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        department_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object buildingCode_ = "";
      /**
       * <code>string Building_Code = 6;</code>
       * @return The buildingCode.
       */
      public java.lang.String getBuildingCode() {
        java.lang.Object ref = buildingCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buildingCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Building_Code = 6;</code>
       * @return The bytes for buildingCode.
       */
      public com.google.protobuf.ByteString
          getBuildingCodeBytes() {
        java.lang.Object ref = buildingCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buildingCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Building_Code = 6;</code>
       * @param value The buildingCode to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buildingCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Building_Code = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingCode() {
        
        buildingCode_ = getDefaultInstance().getBuildingCode();
        onChanged();
        return this;
      }
      /**
       * <code>string Building_Code = 6;</code>
       * @param value The bytes for buildingCode to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buildingCode_ = value;
        onChanged();
        return this;
      }

      private int floorNumber_ = 0;
      /**
       * <code>.protofiles.Person.Floor Floor_Number = 7;</code>
       * @return The enum numeric value on the wire for floorNumber.
       */
      @java.lang.Override public int getFloorNumberValue() {
        return floorNumber_;
      }
      /**
       * <code>.protofiles.Person.Floor Floor_Number = 7;</code>
       * @param value The enum numeric value on the wire for floorNumber to set.
       * @return This builder for chaining.
       */
      public Builder setFloorNumberValue(int value) {
        
        floorNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protofiles.Person.Floor Floor_Number = 7;</code>
       * @return The floorNumber.
       */
      @java.lang.Override
      public protofiles.EmployeeBuilding.Person.Floor getFloorNumber() {
        @SuppressWarnings("deprecation")
        protofiles.EmployeeBuilding.Person.Floor result = protofiles.EmployeeBuilding.Person.Floor.valueOf(floorNumber_);
        return result == null ? protofiles.EmployeeBuilding.Person.Floor.UNRECOGNIZED : result;
      }
      /**
       * <code>.protofiles.Person.Floor Floor_Number = 7;</code>
       * @param value The floorNumber to set.
       * @return This builder for chaining.
       */
      public Builder setFloorNumber(protofiles.EmployeeBuilding.Person.Floor value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        floorNumber_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protofiles.Person.Floor Floor_Number = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFloorNumber() {
        
        floorNumber_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protofiles.Person)
    }

    // @@protoc_insertion_point(class_scope:protofiles.Person)
    private static final protofiles.EmployeeBuilding.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protofiles.EmployeeBuilding.Person();
    }

    public static protofiles.EmployeeBuilding.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protofiles.EmployeeBuilding.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BuildingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protofiles.Building)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string Building_Code = 1;</code>
     * @return The buildingCode.
     */
    java.lang.String getBuildingCode();
    /**
     * <code>string Building_Code = 1;</code>
     * @return The bytes for buildingCode.
     */
    com.google.protobuf.ByteString
        getBuildingCodeBytes();

    /**
     * <code>int32 Total_Floor = 2;</code>
     * @return The totalFloor.
     */
    int getTotalFloor();

    /**
     * <code>int32 Num_Companies = 3;</code>
     * @return The numCompanies.
     */
    int getNumCompanies();

    /**
     * <code>string Cafeteria_Code = 4;</code>
     * @return The cafeteriaCode.
     */
    java.lang.String getCafeteriaCode();
    /**
     * <code>string Cafeteria_Code = 4;</code>
     * @return The bytes for cafeteriaCode.
     */
    com.google.protobuf.ByteString
        getCafeteriaCodeBytes();
  }
  /**
   * Protobuf type {@code protofiles.Building}
   */
  public static final class Building extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protofiles.Building)
      BuildingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Building.newBuilder() to construct.
    private Building(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Building() {
      buildingCode_ = "";
      cafeteriaCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Building();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Building(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              buildingCode_ = s;
              break;
            }
            case 16: {

              totalFloor_ = input.readInt32();
              break;
            }
            case 24: {

              numCompanies_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              cafeteriaCode_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protofiles.EmployeeBuilding.internal_static_protofiles_Building_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protofiles.EmployeeBuilding.internal_static_protofiles_Building_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protofiles.EmployeeBuilding.Building.class, protofiles.EmployeeBuilding.Building.Builder.class);
    }

    public static final int BUILDING_CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object buildingCode_;
    /**
     * <code>string Building_Code = 1;</code>
     * @return The buildingCode.
     */
    @java.lang.Override
    public java.lang.String getBuildingCode() {
      java.lang.Object ref = buildingCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildingCode_ = s;
        return s;
      }
    }
    /**
     * <code>string Building_Code = 1;</code>
     * @return The bytes for buildingCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBuildingCodeBytes() {
      java.lang.Object ref = buildingCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildingCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTAL_FLOOR_FIELD_NUMBER = 2;
    private int totalFloor_;
    /**
     * <code>int32 Total_Floor = 2;</code>
     * @return The totalFloor.
     */
    @java.lang.Override
    public int getTotalFloor() {
      return totalFloor_;
    }

    public static final int NUM_COMPANIES_FIELD_NUMBER = 3;
    private int numCompanies_;
    /**
     * <code>int32 Num_Companies = 3;</code>
     * @return The numCompanies.
     */
    @java.lang.Override
    public int getNumCompanies() {
      return numCompanies_;
    }

    public static final int CAFETERIA_CODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object cafeteriaCode_;
    /**
     * <code>string Cafeteria_Code = 4;</code>
     * @return The cafeteriaCode.
     */
    @java.lang.Override
    public java.lang.String getCafeteriaCode() {
      java.lang.Object ref = cafeteriaCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cafeteriaCode_ = s;
        return s;
      }
    }
    /**
     * <code>string Cafeteria_Code = 4;</code>
     * @return The bytes for cafeteriaCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCafeteriaCodeBytes() {
      java.lang.Object ref = cafeteriaCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cafeteriaCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBuildingCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, buildingCode_);
      }
      if (totalFloor_ != 0) {
        output.writeInt32(2, totalFloor_);
      }
      if (numCompanies_ != 0) {
        output.writeInt32(3, numCompanies_);
      }
      if (!getCafeteriaCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cafeteriaCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBuildingCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, buildingCode_);
      }
      if (totalFloor_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, totalFloor_);
      }
      if (numCompanies_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, numCompanies_);
      }
      if (!getCafeteriaCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cafeteriaCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protofiles.EmployeeBuilding.Building)) {
        return super.equals(obj);
      }
      protofiles.EmployeeBuilding.Building other = (protofiles.EmployeeBuilding.Building) obj;

      if (!getBuildingCode()
          .equals(other.getBuildingCode())) return false;
      if (getTotalFloor()
          != other.getTotalFloor()) return false;
      if (getNumCompanies()
          != other.getNumCompanies()) return false;
      if (!getCafeteriaCode()
          .equals(other.getCafeteriaCode())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUILDING_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingCode().hashCode();
      hash = (37 * hash) + TOTAL_FLOOR_FIELD_NUMBER;
      hash = (53 * hash) + getTotalFloor();
      hash = (37 * hash) + NUM_COMPANIES_FIELD_NUMBER;
      hash = (53 * hash) + getNumCompanies();
      hash = (37 * hash) + CAFETERIA_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCafeteriaCode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protofiles.EmployeeBuilding.Building parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protofiles.EmployeeBuilding.Building parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protofiles.EmployeeBuilding.Building parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protofiles.EmployeeBuilding.Building parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protofiles.EmployeeBuilding.Building parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protofiles.EmployeeBuilding.Building parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protofiles.EmployeeBuilding.Building parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protofiles.EmployeeBuilding.Building parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protofiles.EmployeeBuilding.Building parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protofiles.EmployeeBuilding.Building parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protofiles.EmployeeBuilding.Building parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protofiles.EmployeeBuilding.Building parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protofiles.EmployeeBuilding.Building prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protofiles.Building}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protofiles.Building)
        protofiles.EmployeeBuilding.BuildingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protofiles.EmployeeBuilding.internal_static_protofiles_Building_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protofiles.EmployeeBuilding.internal_static_protofiles_Building_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protofiles.EmployeeBuilding.Building.class, protofiles.EmployeeBuilding.Building.Builder.class);
      }

      // Construct using protofiles.EmployeeBuilding.Building.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        buildingCode_ = "";

        totalFloor_ = 0;

        numCompanies_ = 0;

        cafeteriaCode_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protofiles.EmployeeBuilding.internal_static_protofiles_Building_descriptor;
      }

      @java.lang.Override
      public protofiles.EmployeeBuilding.Building getDefaultInstanceForType() {
        return protofiles.EmployeeBuilding.Building.getDefaultInstance();
      }

      @java.lang.Override
      public protofiles.EmployeeBuilding.Building build() {
        protofiles.EmployeeBuilding.Building result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protofiles.EmployeeBuilding.Building buildPartial() {
        protofiles.EmployeeBuilding.Building result = new protofiles.EmployeeBuilding.Building(this);
        result.buildingCode_ = buildingCode_;
        result.totalFloor_ = totalFloor_;
        result.numCompanies_ = numCompanies_;
        result.cafeteriaCode_ = cafeteriaCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protofiles.EmployeeBuilding.Building) {
          return mergeFrom((protofiles.EmployeeBuilding.Building)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protofiles.EmployeeBuilding.Building other) {
        if (other == protofiles.EmployeeBuilding.Building.getDefaultInstance()) return this;
        if (!other.getBuildingCode().isEmpty()) {
          buildingCode_ = other.buildingCode_;
          onChanged();
        }
        if (other.getTotalFloor() != 0) {
          setTotalFloor(other.getTotalFloor());
        }
        if (other.getNumCompanies() != 0) {
          setNumCompanies(other.getNumCompanies());
        }
        if (!other.getCafeteriaCode().isEmpty()) {
          cafeteriaCode_ = other.cafeteriaCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protofiles.EmployeeBuilding.Building parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protofiles.EmployeeBuilding.Building) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object buildingCode_ = "";
      /**
       * <code>string Building_Code = 1;</code>
       * @return The buildingCode.
       */
      public java.lang.String getBuildingCode() {
        java.lang.Object ref = buildingCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buildingCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Building_Code = 1;</code>
       * @return The bytes for buildingCode.
       */
      public com.google.protobuf.ByteString
          getBuildingCodeBytes() {
        java.lang.Object ref = buildingCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buildingCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Building_Code = 1;</code>
       * @param value The buildingCode to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buildingCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Building_Code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingCode() {
        
        buildingCode_ = getDefaultInstance().getBuildingCode();
        onChanged();
        return this;
      }
      /**
       * <code>string Building_Code = 1;</code>
       * @param value The bytes for buildingCode to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buildingCode_ = value;
        onChanged();
        return this;
      }

      private int totalFloor_ ;
      /**
       * <code>int32 Total_Floor = 2;</code>
       * @return The totalFloor.
       */
      @java.lang.Override
      public int getTotalFloor() {
        return totalFloor_;
      }
      /**
       * <code>int32 Total_Floor = 2;</code>
       * @param value The totalFloor to set.
       * @return This builder for chaining.
       */
      public Builder setTotalFloor(int value) {
        
        totalFloor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Total_Floor = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalFloor() {
        
        totalFloor_ = 0;
        onChanged();
        return this;
      }

      private int numCompanies_ ;
      /**
       * <code>int32 Num_Companies = 3;</code>
       * @return The numCompanies.
       */
      @java.lang.Override
      public int getNumCompanies() {
        return numCompanies_;
      }
      /**
       * <code>int32 Num_Companies = 3;</code>
       * @param value The numCompanies to set.
       * @return This builder for chaining.
       */
      public Builder setNumCompanies(int value) {
        
        numCompanies_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Num_Companies = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumCompanies() {
        
        numCompanies_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object cafeteriaCode_ = "";
      /**
       * <code>string Cafeteria_Code = 4;</code>
       * @return The cafeteriaCode.
       */
      public java.lang.String getCafeteriaCode() {
        java.lang.Object ref = cafeteriaCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cafeteriaCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Cafeteria_Code = 4;</code>
       * @return The bytes for cafeteriaCode.
       */
      public com.google.protobuf.ByteString
          getCafeteriaCodeBytes() {
        java.lang.Object ref = cafeteriaCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cafeteriaCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Cafeteria_Code = 4;</code>
       * @param value The cafeteriaCode to set.
       * @return This builder for chaining.
       */
      public Builder setCafeteriaCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cafeteriaCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Cafeteria_Code = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCafeteriaCode() {
        
        cafeteriaCode_ = getDefaultInstance().getCafeteriaCode();
        onChanged();
        return this;
      }
      /**
       * <code>string Cafeteria_Code = 4;</code>
       * @param value The bytes for cafeteriaCode to set.
       * @return This builder for chaining.
       */
      public Builder setCafeteriaCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cafeteriaCode_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protofiles.Building)
    }

    // @@protoc_insertion_point(class_scope:protofiles.Building)
    private static final protofiles.EmployeeBuilding.Building DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protofiles.EmployeeBuilding.Building();
    }

    public static protofiles.EmployeeBuilding.Building getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Building>
        PARSER = new com.google.protobuf.AbstractParser<Building>() {
      @java.lang.Override
      public Building parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Building(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Building> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Building> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protofiles.EmployeeBuilding.Building getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protofiles_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protofiles_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protofiles_Building_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protofiles_Building_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026EmployeeBuilding.proto\022\nprotofiles\"\247\002\n" +
      "\006Person\022\023\n\013Employee_ID\030\001 \001(\005\022\022\n\nFirst_Na" +
      "me\030\002 \001(\t\022\021\n\tLast_Name\030\003 \001(\t\022\r\n\005Email\030\004 \001" +
      "(\t\022\022\n\nDepartment\030\005 \001(\t\022\025\n\rBuilding_Code\030" +
      "\006 \001(\t\022.\n\014Floor_Number\030\007 \001(\0162\030.protofiles" +
      ".Person.Floor\"w\n\005Floor\022\013\n\007UNKNOWN\020\000\022\007\n\003O" +
      "NE\020\001\022\007\n\003TWO\020\002\022\t\n\005THREE\020\003\022\010\n\004FOUR\020\004\022\010\n\004FI" +
      "VE\020\005\022\007\n\003SIX\020\006\022\t\n\005SEVEN\020\007\022\t\n\005EIGHT\020\010\022\010\n\004N" +
      "INE\020\t\022\007\n\003TEN\020\n\"e\n\010Building\022\025\n\rBuilding_C" +
      "ode\030\001 \001(\t\022\023\n\013Total_Floor\030\002 \001(\005\022\025\n\rNum_Co" +
      "mpanies\030\003 \001(\005\022\026\n\016Cafeteria_Code\030\004 \001(\tb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protofiles_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protofiles_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protofiles_Person_descriptor,
        new java.lang.String[] { "EmployeeID", "FirstName", "LastName", "Email", "Department", "BuildingCode", "FloorNumber", });
    internal_static_protofiles_Building_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protofiles_Building_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protofiles_Building_descriptor,
        new java.lang.String[] { "BuildingCode", "TotalFloor", "NumCompanies", "CafeteriaCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
